"""empty message

Revision ID: 6f7f180e2607
Revises: 24dc32e166b4
Create Date: 2024-11-10 10:32:31.219687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7f180e2607'
down_revision: Union[str, None] = '24dc32e166b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'telegram_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('telegram_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
