"""empty message

Revision ID: 4bf7978cef24
Revises: 814878bbd4d7
Create Date: 2024-11-09 21:03:08.027937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf7978cef24'
down_revision: Union[str, None] = '814878bbd4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_result_table', sa.Column('question_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_question_result_table', 'question_table', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_survey_result_table', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('user_survey_result_table_user_id_fkey', 'user_survey_result_table', type_='foreignkey')
    op.create_foreign_key(None, 'user_survey_result_table', 'user_table', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_survey_result_table', type_='foreignkey')
    op.create_foreign_key('user_survey_result_table_user_id_fkey', 'user_survey_result_table', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_survey_result_table', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'user_question_result_table', type_='foreignkey')
    op.drop_column('user_question_result_table', 'question_id')
    # ### end Alembic commands ###
