"""empty message

Revision ID: d34348da5a39
Revises: 0ce9bddba381
Create Date: 2024-11-09 15:18:36.252381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34348da5a39'
down_revision: Union[str, None] = '0ce9bddba381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_table',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expire_datetime', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_table_id'), 'code_table', ['id'], unique=False)
    op.drop_column('user_table', 'email_confirmation_code')
    op.drop_column('user_table', 'patronymic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('email_confirmation_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_code_table_id'), table_name='code_table')
    op.drop_table('code_table')
    # ### end Alembic commands ###
