"""empty message

Revision ID: bed18f43743e
Revises: ccde1a5c5a64
Create Date: 2024-11-09 15:18:29.458783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed18f43743e'
down_revision: Union[str, None] = 'ccde1a5c5a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'patronymic')
    op.drop_column('user_table', 'email_confirmation_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('email_confirmation_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
