"""empty message

Revision ID: bb4dab437029
Revises: 1ec8497da18c
Create Date: 2024-11-10 00:09:00.161161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4dab437029'
down_revision: Union[str, None] = '1ec8497da18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('survey_table_document_id_fkey', 'survey_table', type_='foreignkey')
    op.drop_column('survey_table', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_table', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('survey_table_document_id_fkey', 'survey_table', 'survey_document_table', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
