"""empty message

Revision ID: 72e7f0f121a7
Revises: 346e1937fddd
Create Date: 2024-11-10 10:32:19.469207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e7f0f121a7'
down_revision: Union[str, None] = '346e1937fddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'telegram_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('telegram_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
